### ISSUE TITLE
Add typings

### ISSUE THREAD

**Issue by pke** [jeffersonmourak/jest-fuzz#17]
Would be nice to have some typings for the lib

**Comment by jeffersonmourak** [comment]
Sure, you sent this right when I was updating it.
I had lost access to NPM for a few years, and now I have access back. so I'll publish this update real soon.

**Comment by pke** [comment]
Oh how cool! Thanks for coming back to this useful project!

I have a few more ideas from my real world usage of it for a few days already. 
May I create issues and maybe working on a few PRs myself?

**Comment by jeffersonmourak** [comment]
Sure, you're more than welcome, I'm planning to release a final V1, but it's in the beginning. I'll Invite you as a collaborator 😄
